### ISSUE TITLE
looks like 'repositories' custom settings is ignored

### ISSUE THREAD

**Issue by khvatov** [chef-cookbooks/maven#38]
I am tying to point to our local maven repo (Nexus) to pull the artifact, but I get an error complaining about not being able to connect to http://repo.maven.apache.org (connection refused) The machine I'm trying to run the recipe is behind the firewall. 
I trying to run an example:

```
maven 'mysql-connector-java' do 
  group_id 'mysql' 
  version '5.1.19' 
  repositories ['http://company/local/repo']
  dest '/home/someuser/'
  owner 'someuser'
end
```

I get 

```
[ERROR] Plugin org.apache.maven.plugins:maven-dependency-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:2.4: Could not transfer artifact org.apache.maven.plugins:maven-dependency-plugin:pom:2.4 from/to central (http://repo.maven.apache.org/maven2): Connection to http://repo.maven.apache.org refused: Connection timed out -> [Help 1]
```

Is there any other way to point to the custom repo?
NOTE: Platform RHEL. Chef: 11.12.4

**Comment by tas50** [comment]
Can you try this with the latest cookbook release. I made a change to how we evaluate this value.
