### ISSUE TITLE
Setting an 'owner' fails if a user's group is not the same as username  e.g. nobody:nogroup

### ISSUE THREAD

**Issue by khvatov** [chef-cookbooks/maven#39]
because default provider assumes the new owner belongs to the group with the same name e.g. 
user:user. In my case I have group 'users' and user 'user1'.

around line 66
```
 owner new_resource.owner
 group new_resource.owner
```

'owner' is not being set properly

Platform RHEL
Chef: 11.12.4

**Comment by ShibaBandit** [comment]
Also ran into this problem.

**Comment by tas50** [comment]
@khvatov @ShibaBandit The 2.0.1 has resolved this by adding a property for group,which defaults to root's group.  Give it a try.
