### ISSUE TITLE
Cookbook fails to run with error undefined method `win_install_dir'

### ISSUE THREAD

**Issue by praste** [chef-cookbooks/maven#54]
Cookbook fails to run on Ubuntu machine with error undefined method `win_install_dir'
is this attribute newest addition to ark resource?

**Comment by praste** [comment]
I think easiest way to fix this is to update metadata.rb and Berkfile to use latest version of ark

**Comment by cheeseplus** [comment]
Versions were bumped and this should no longer be an issue.
