### ISSUE TITLE
Java Cookbook dependency is too restrictive.

### ISSUE THREAD

**Issue by rhass-r7** [chef-cookbooks/maven#56]
The current version of the Java cookbook is 1.31.1 and the metadata restricts the version to '~> 1.13'. The desired behavior is to change the restriction to '>= 1.13'

**Comment by rhass-r7** [comment]
Submitted PR #57

**Comment by shaiguitar** [comment]
Hey, any feedback for open PR's? There are 17 pending pull requests in https://github.com/opscode-cookbooks/maven/pulls ... if there is a maintenance hassle on this I would be happy to contribute time reviewing changes, feedback etc. Thanks for this repo!

**Comment by jeffbyrnes** [comment]
I’d argue that that version restriction is sensible; preventing this cookbook from accidentally bringing in a breaking version of the java cookbook (i.e., `>= v2.0.0`). This version pin will prevent any version up to, but not including, `v2.0.0`.

**Comment by tas50** [comment]
As noted in the PR, this pin is actually exactly what we want.  It brings in 1.13 as a minimum, but keeps us from accidentally pulling in 2.0 which may break this cookbook when its released.
