### ISSUE TITLE
fails to run due to Ark error

### ISSUE THREAD

**Issue by jacek99** [chef-cookbooks/maven#65]
Running this on Fedora 22, trying to just include the maven recipe to get it installed, fails with an Ark error:

  ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/gso-pipeline/recipes/jenkins_master.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `win_install_dir' for Chef::Resource::Ark
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/maven/recipes/default.rb:32:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/maven/recipes/default.rb:28:in `from_file'
         /tmp/kitchen/cache/cookbooks/gso-pipeline/recipes/jenkins_master.rb:18:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/maven/recipes/default.rb:
       
        25:  
        26:  mvn_version = node['maven']['version'].to_s
        27:  
        28:  ark 'maven' do
        29:    url             node['maven'][mvn_version]['url']
        30:    checksum        node['maven'][mvn_version]['checksum']
        31:    home_dir        node['maven']['m2_home']
        32>>   win_install_dir node['maven']['m2_home']
        33:    version         node['maven'][mvn_version]['version']
        34:    append_env_path true
        35:  end
        36:  
        37:  if node['platform_family'] === 'windows'
        38:    env 'M2_HOME' do
        39:      value node['maven']['m2_home']
        40:      action :create
        41:    end

**Comment by arifcse019** [comment]
I am experiencing the same error on centOS 6.5

**Comment by arifcse019** [comment]
may be its the solution: https://github.com/opscode-cookbooks/maven/issues/54

**Comment by tas50** [comment]
I have a branch to remove Maven 2 support that also bumps the ark requirement to 0.9.0 which will fix this issue.
