### ISSUE TITLE
Not a huge issue, more of a hey so you know. /usr/local/maven-3.1.1 directory created for maven-3.3.3

### ISSUE THREAD

**Issue by LevonBecker** [chef-cookbooks/maven#66]
Not a huge issue, more of a hey so you know. 
/usr/local/maven-3.1.1 directory created for maven-3.3.3
mvn -v shows it is indeed 3.3.3

CentOS 6.6
Chef_Zero
Test-Kitchen
Vagrant

**Comment by LevonBecker** [comment]
also, sure would be nice to be able to give full version and you default to the Apache URL download and skip the ark checksum if don't care if sha256sum matches for a dev box to have maven blah.

**Comment by tas50** [comment]
@LevonBecker This should be resolved with how the version attribute is handled in the latest version.  Give it a try and feel free to open this back up if it's still an issue.
