### ISSUE TITLE
maven LWRP always reports updated_by_last_action(true)

### ISSUE THREAD

**Issue by jeffbyrnes** [chef-cookbooks/maven#68]
At [line 72 of the provider code](https://github.com/chef-cookbooks/maven/blob/v1.3.0/providers/default.rb#L72), you can see that the provider always reports it was updated, which can result in undesirable behavior (e.g., restart a `service` via a `subscribes` on an instance of the LWRP, which will restart the service on every Chef run).

You can see a great example with the [cron_d cookbook in the Chef docs](https://docs.chef.io/lwrp_custom_provider.html#cron-d).

Wondering how this might be modified to improve this behavior, and be more idempotent (i.e., not report updated if nothing happened).

**Comment by tas50** [comment]
This should be fixed on master now
