### ISSUE TITLE
Maven 2 has reached end of life so default url attribute should be updated to reflect this

### ISSUE THREAD

**Issue by graeme-forbes-tmg** [chef-cookbooks/maven#69]
As per the message here: http://apache.mirrors.tds.net/maven/maven-2/
The maven 2 default attribute root path should be set to http://archive.apache.org/dist/maven/binaries/apache-maven-#{node['maven']['2']['version']}-bin.tar.gz

Currently a chef run will break if it depends on this version. Arguably this could also be left broken as it is end of life.

**Comment by tas50** [comment]
I have a branch to remove Maven 2 at the moment that should be merged / releases next week.
