### ISSUE TITLE
add option for setting owner for maven

### ISSUE THREAD

**Issue by stevegal** [chef-cookbooks/maven#82]
Cookbook: 4.0.1
Chef: 12

when installing maven I cannot specify a user/group other than root, limiting the use cases for maven installed in this way

**Comment by iennae** [comment]
@stevegal it looks like you can set the user/group with the attribute owner and group for the maven resource. Check out example: https://github.com/chef-cookbooks/maven/blob/master/test/fixtures/cookbooks/test/recipes/default.rb#L30

Please let us know if you are having issues with this or if there is something else you are asking about in this issue.

**Comment by stevegal** [comment]
that's cool for downloading dependencies from the cookbook.
I was talking about if you need to use maven for other purposes rather than just the downloading a specific thing, for example for doing a build.
