### ISSUE TITLE
Maven version 3.5.0 no longer in Apache mirrors

### ISSUE THREAD

**Issue by sfiggins** [chef-cookbooks/maven#88]
### Cookbook version
5.0.1

### Chef-client version
All

### Platform Details
All Linux

### Scenario:
Install maven with include_recipe 'maven'

### Steps to Reproduce:
Attempt to converge

### Expected Result:
Maven is installed

### Actual Result:
Receive an error when remote_file attempts to retrieve the maven tar.gz file, as the resource is no longer hosted on the mirror. 

Confirmed no 3.5.0 version at 

http://apache.mirrors.tds.net/maven/maven-3/

**Comment by tas50** [comment]
This is fixed in 5.0.2
