### ISSUE TITLE
Unable to Download Maven file apache-maven-3.5.0-bin.tar.gz

### ISSUE THREAD

**Issue by MarcusMaximus** [chef-cookbooks/maven#91]
### Cookbook version
maven (5.0.1)

### Chef-client version
Chef: 12.17.44

### Platform Details
OS: Linux Mint 18.1 Serena x86_64

### Scenario:
Provision a bamboo agent with chef which uses the maven cookbook

### Steps to Reproduce:
Attempt to use this cookbook

### Expected Result:
Maven file will not be available at http://apache.mirrors.tds.net/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz

### Actual Result:
Recipe: maven::default
                                         * ark[maven] action install
                                           * directory[/usr/local/maven-3.5.0] action create
                                             - create new directory /usr/local/maven-3.5.0
                                           * remote_file[/var/chef/cache/maven-3.5.0.tar.gz] action create[2017-11-13T00:16:25+00:00] WARN: remote_file[/var/chef/cache/maven-3.5.0.tar.gz] cannot be downloaded from http://apache.mirrors.tds.net/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz: 404 "Not Found"

**Comment by MarcusMaximus** [comment]
node.default['maven']['url'] = "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.tar.gz" fixes the issue.

**Comment by tas50** [comment]
@MarcusMaximus This is fixed in the 5.0.3 release. Give that one a try
